apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: springboot-build
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Checkout code
        uses: cloudbees-io/checkout@v1
