apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: springboot-build
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Checkout code
        uses: cloudbees-io/checkout@v1
      - name: Build, test, and publish reports/artifacts
        kind: build
        uses: docker://gradle:7.6.2-jdk17
        run: |
          chmod +x ./gradlew
          ./gradlew clean build
      - name: Test
        kind: test
        uses: docker://gradle:7.6.2-jdk17
        run: |
          chmod +x ./gradlew
          ./gradlew  test
