apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: springboot-build
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Checkout code
        uses: cloudbees-io/checkout@v1

      - name: Setup and build
        uses: docker://gradle:7.6.2-jdk17
        run: |
          chmod +x ./gradlew
          ./gradlew build
          ./gradlew test