apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: springboot-build
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Checkout code
        uses: cloudbees-io/checkout@v1

      - name: Build and test
        uses: docker://gradle:7.6.2-jdk17
        run: |
          chmod +x ./gradlew
          ./gradlew clean build test
          mkdir -p /cloudbees/reports/junit
          cp build/test-results/test/*.xml /cloudbees/reports/junit/

      - name: Upload JAR artifact
        uses: cloudbees-io/artifact@v1
        with:
          path: build/libs/*.jar